<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\**" />
    <Compile Remove="ValueObjects\**" />
    <EmbeddedResource Remove="Models\**" />
    <EmbeddedResource Remove="ValueObjects\**" />
    <None Remove="Models\**" />
    <None Remove="ValueObjects\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GymForge.Contracts\GymForge.Contracts.csproj" />
    <ProjectReference Include="..\GymForge.Shared\GymForge.Shared.csproj" />
  </ItemGroup>

</Project>
