<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Persistance\**" />
    <EmbeddedResource Remove="Persistance\**" />
    <None Remove="Persistance\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GymForge.Contracts\GymForge.Contracts.csproj" />
    <ProjectReference Include="..\GymForge.Domain\GymForge.Domain.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\GymForge.Shared\GymForge.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CloudinaryDotNet" Version="1.28.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.2" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.2">
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		  <PrivateAssets>all</PrivateAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.2" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="10.0.2" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.2" />
	  <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0-preview.2.25163.2" />
	  <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0-preview.1.25151.1" />
	  <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
