using System;

namespace GymForge.Domain.Entities
{
    public class MealLogEntry : BaseEntity
    {
        public Guid DietLogId { get; set; }
        public DietLog? DietLog { get; set; }

        public string MealType { get; set; } = string.Empty; // e.g. "Breakfast", "Lunch", "Snack"
        public string FoodName { get; set; } = string.Empty;

        public int Calories { get; set; }
        public decimal Protein { get; set; }
        public decimal Carbs { get; set; }
        public decimal Fats { get; set; }

        // If this entry was generated by completing a planned meal
        public Guid? SourceDietPlanMealId { get; set; }
        
        // For 3rd party integration
        public string? ExternalFoodId { get; set; }
        public decimal ServingSize { get; set; } = 1;
        public string ServingUnit { get; set; } = "serving";
    }
}
